require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'lib/**/*'
  DisplayCopNames: true
  NewCops: enable
Layout/HashAlignment:
  Enabled: false
Layout/EmptyLines:
  Enabled: true
  Exclude:
    - 'Gemfile'
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/ExtraSpacing:
  Enabled: true
  Exclude:
    - 'db/migrate/*'
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  Exclude:
    - 'config/**/*'
Layout/LineLength:
  Enabled: true
  Max:     120
  Exclude:
    - 'config/**/*'
Metrics/AbcSize:
  Enabled: true
  Max: 25
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
Metrics/ClassLength:
  Enabled: true
  Max: 120
Metrics/MethodLength:
  Enabled: true
  Max: 25
Rspec/DescribeClass:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment: 
  Enabled: false